#: import MainMenu menu.MainMenu

<MainMenu>:
    Button:
        text: "Start Game"
        size_hint: None, None
        size: 200, 50
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        on_press: root.start_app()

<Background>:
    canvas.before:
        Rectangle:
            size: self.size
            pos: self.pos
            source: "background.png"

<Button>:
    size_hint: None, None
    size: 200, 50

